const currencyCodes = {
    DZD: "Algerian dinar   (DZD)",
    AUD: "Australian dollar   (AUD)",
    BWP: "Botswana pula   (BWP)",
    BRL: "Brazilian real   (BRL)",
    BND: "Brunei dollar   (BND)",
    CAD: "Canadian dollar   (CAD)",
    CLP: "Chilean peso   (CLP)",
    CNY: "Chinese yuan   (CNY)",
    CZK: "Czech koruna   (CZK)",
    DKK: "Danish krone   (DKK)",
    EUR: "Euro   (EUR)",
    INR: "Indian rupee   (INR)",
    ILS: "Israeli New Shekel   (ILS)",
    JPY: "Japanese yen   (JPY)",
    KRW: "Korean won   (KRW)",
    KWD: "Kuwaiti dinar   (KWD)",
    MYR: "Malaysian ringgit   (MYR)",
    MUR: "Mauritian rupee   (MUR)",
    MXN: "Mexican peso   (MXN)",
    NZD: "New Zealand dollar   (NZD)",
    NOK: "Norwegian krone   (NOK)",
    OMR: "Omani rial   (OMR)",
    PEN: "Peruvian sol   (PEN)",
    PHP: "Philippine peso   (PHP)",
    PLN: "Polish zloty   (PLN)",
    QAR: "Qatari riyal   (QAR)",
    RUB: "Russian ruble   (RUB)",
    SAR: "Saudi Arabian riyal   (SAR)",
    SGD: "Singapore dollar   (SGD)",
    ZAR: "South African rand   (ZAR)",
    SEK: "Swedish krona   (SEK)",
    CHF: "Swiss franc   (CHF)",
    THB: "Thai baht   (THB)",
    TTD: "Trinidadian dollar   (TTD)",
    AED: "U.A.E. dirham   (AED)",
    GBP: "U.K. pound   (GBP)",
    USD: "U.S. dollar   (USD)",
    UYU: "Uruguayan peso   (UYU)",
  };

export {currencyCodes};